# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# RuboCop configuration
AllCops:
  # Use GitHub format by default for better CI/CD integration
  DefaultFormatter: github
  DisplayCopNames: true

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
