json.id listing.id
json.title listing.title
json.description listing.description
json.price listing.price
json.purpose listing.purpose
json.condition listing.condition
json.status listing.status
json.user_id listing.user_id
json.category_id listing.category_id
json.language listing.language
json.created_at listing.created_at
json.updated_at listing.updated_at
